#ifndef _USER_BLE_DEV_H_
#define _USER_BLE_DEV_H_

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "esp_gatt_defs.h"

/* Attributes State Machine */
enum{
    IDX_SVC_DIS,

    IDX_SVC_DIS_CHAR_SYSTEM_ID,
    IDX_SVC_DIS_CHAR_SYSTEM_ID_VAL,

    IDX_SVC_DIS_CHAR_MODEL_NUMBER_STRING,
    IDX_SVC_DIS_CHAR_MODEL_NUMBER_STRING_VAL,

    IDX_SVC_DIS_CHAR_SERIAL_NUMBER_STRING,
    IDX_SVC_DIS_CHAR_SERIAL_NUMBER_STRING_VAL,

    IDX_SVC_DIS_CHAR_FIRMWARE_REVISION_STRING,
    IDX_SVC_DIS_CHAR_FIRMWARE_REVISION_STRING_VAL,

    IDX_SVC_DIS_CHAR_HARDWARE_REVISION_STRING,
    IDX_SVC_DIS_CHAR_HARDWARE_REVISION_STRING_VAL,

    IDX_SVC_DIS_CHAR_SOFTWARE_REVISION_STRING,
    IDX_SVC_DIS_CHAR_SOFTWARE_REVISION_STRING_VAL,

    IDX_SVC_DIS_CHAR_MANUFACTURER_NAME_STRING,
    IDX_SVC_DIS_CHAR_MANUFACTURER_NAME_STRING_VAL,

    IDX_SVC_DIS_MAX

};

const esp_gatts_attr_db_t gatt_db_DIS[IDX_SVC_DIS_MAX];
uint16_t DIS_handle_table[IDX_SVC_DIS_MAX];


#endif
