#ifndef _USER_BLE_FTMS_H_
#define _USER_BLE_FTMS_H_

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "esp_gatt_defs.h"
#include "fitness_machine_field.h"

typedef enum
{
    SPORTS_TYPE_BIKE = 0,         // 单车类型
    SPORTS_TYPE_CROSSTRAINER = 1, // 椭圆机类型
    SPORTS_TYPE_TREADMILL = 2,    // 跑步机类型
    SPORTS_TYPE_ROWER = 3,        // 划船机机类型
}FTMS_SPORTS_TYPE_t;

/* Attributes State Machine */
enum
{
    IDX_SVC,

    IDX_CHAR_GATT_UUID_FITNESS_MACHINE_FEATURE,
    IDX_CHAR_GATT_UUID_FITNESS_MACHINE_FEATURE_VAL,

    IDX_CHAR_GATT_UUID_SPORTS_DATA,
    IDX_CHAR_GATT_UUID_SPORTS_DATA_VAL,
    IDX_CHAR_GATT_UUID_SPORTS_DATA_CFG,

    IDX_CHAR_GATT_UUID_TRAINING_STATUS,
    IDX_CHAR_VAL_GATT_UUID_TRAINING_STATUS,
    IDX_CHAR_CFG_GATT_UUID_TRAINING_STATUS,

    IDX_CHAR_GATT_UUID_SUPPORT_SPEED_RANGE,
    IDX_CHAR_VAL_GATT_UUID_SUPPORT_SPEED_RANGE,

    IDX_CHAR_GATT_UUID_SUPPORT_RESISTANCE_LEVEL_RANGE,
    IDX_CHAR_VAL_GATT_UUID_SUPPORT_RESISTANCE_LEVEL_RANGE,

    IDX_CHAR_GATT_UUID_SUPPORT_POWER_RANGE,
    IDX_CHAR_VAL_GATT_UUID_SUPPORT_POWER_RANGE,

    IDX_CHAR_GATT_UUID_FITNESS_MACHINE_CONTROL_POINT,
    IDX_CHAR_VAL_GATT_UUID_FITNESS_MACHINE_CONTROL_POINT,
    IDX_CHAR_CFG_GATT_UUID_FITNESS_MACHINE_CONTROL_POINT,

    IDX_CHAR_GATT_UUID_FITNESS_MACHINE_STATUS,
    IDX_CHAR_VAL_GATT_UUID_FITNESS_MACHINE_STATUS,
    IDX_CHAR_CFG_GATT_UUID_FITNESS_MACHINE_STATUS,

    IDX_CHAR_GATT_UUID_FITNESS_EXTENSION_DATA,
    IDX_CHAR_VAL_GATT_UUID_FITNESS_EXTENSION_DATA,

    HRS_IDX_NB,
};

esp_gatts_attr_db_t gatt_db_ftms[HRS_IDX_NB];
/**
 * @brief 根据设备类型，选择对应的运动数据特征值
 *
 * @note  FTMS_SPORTS_TYPE是运动类型的美剧，必须用此类型
 *
 * @param FTMS_SPORTS_TYPE_t 运动数据类型
 *
 * @return void
 */
void set_ftms_sports_type(FTMS_SPORTS_TYPE_t type);

#endif
